modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "All rights reserved"

[[mods]]
modId = "playerplates"
version = "${version}"
displayName = "Player Plates"
authors = "Gaz"
description = '''
Obsidian pressure plates and mossy plates
'''
#logoFile = ""

[[dependencies.playerplates]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playerplates]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playerplates]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"