modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All rights reserved"

[[mods]]
modId = "playerplates"
version = "${version}"
displayName = "Player Plates"
authors = "Gaz"
description = '''
Obsidian pressure plates and mossy plates
'''
#logoFile = ""

[[dependencies.playerplates]]
modId = "neoforge"
required = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playerplates]]
modId = "minecraft"
required = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playerplates]]
modId = "architectury"
required = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"